version: "2.4"

services:
  aomdServer:
    image: aomd-server/portfolio:0.2
    volumes:
      - ./services/portfolio/build/libs/aomd-server.jar:/HOME/spring/app.jar
    ports:
      - 8080:8080
    mem_limit: 350m
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/aomd-db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      mysql:
        condition: service_healthy
  
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: aomd-db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    healthcheck:
      test: "/usr/bin/mysql -uuser -p1234 --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 5s
      retries: 10
