spring:
  config:
    import: secret.yml
  datasource:
    url: jdbc:h2:tcp://localhost/~/Desktop/Dev/local/Spring/security
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      initialization-fail-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: create-drop
    logging.level:
      org.hibernate.SQL: debug
#    defer-datasource-initialization: false
  sql:
    init:
      mode: always
  profiles:
    group:
      local: "local"
      dev: "dev"
      prod: "prod"

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
---
spring:
  config:
    activate:
      on-profile: "dev"
    import: mysql-datasource.yml
  jpa:
    hibernate:
      ddl-auto: create
    logging.level:
      org.hibernate.SQL: debug
    
---
spring:
  config:
    activate:
      on-profile: "prod"
  jpa:
    hibernate:
      ddl-auto: create