# Default values for aomd-server.

replicaCount: 2

image:
  repository: hyun0404woo/aomd-server
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""
  
secretName: aomd-secret

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30808

ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations: 
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - paths:
        - path: /api
          pathType: Prefix
        - path: /swagger-ui
          pathType: Prefix
        - path: /v3/api-docs
          pathType: Prefix
        - path: /actuator
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

application:
  mode: prod
  
db:
  username: root
  passwordKey: mysql-root-password
  
  