name: aomdCI

on:
  pull_request:
    branches:
      - main
    types: [ closed ]
  push:
    branches:
      - main
    types: [ closed ]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
      - run: echo The PR was merged
      
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.AOMD_PRIVATE }}
          submodules: true
          
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Grant execute permission for gradlew
        shell: bash
        run: chmod +x ./gradlew

      - name: Build with Gradle
        shell: bash
        run: ./gradlew -Dspring.profiles.active=prod clean build
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./services/portfolio/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/aomd-server:latest