name: aomdCI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches:
      - main
    types: [ closed ]

env:
  git_tag: ${{ github.sha }}

jobs:
  if_merged:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
      - run: echo The PR was merged
      
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.AOMD_PRIVATE }}
          submodules: recursive
          
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Grant execute permission for gradlew
        shell: bash
        run: chmod +x ./gradlew

      - name: Build with Gradle
        shell: bash
        run: |
            ./gradlew -Dspring.profiles.active=prod clean build
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./services/portfolio/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/aomd-server:latest
  
  update-argocd-manifest:
    needs: if_merged
    runs-on: ubuntu-20.04
    
    defaults:
      run:
        working-directory: ./prod/aomd-server

    steps:
    - name: Checkout argocd-deploy branch
      uses: actions/checkout@v3
      with:
        ref: argocd-deploy
        token: ${{ secrets.AOMD_PRIVATE }}
        submodules: recursive

    - name: Change git-tag.yaml
      run: |
        cat <<EOF > git-tag.yaml
        image:
          tag: ${{ env.git_tag }}
        EOF

    - name: New git tag push
      run: |
        git config --global user.email "GitHub Actions Bot@github.com"
        git config --global user.name "GitHub Actions Bot"
        git add git-tag.yaml
        git commit -m "update git tag"
        git pull origin argocd-deploy
        git push origin argocd-deploy